<?php  
//connect to mysql server with host,username,password
require "connection-graph.php";

//Debug function (Hit F12 in browser) and usage: debug_to_console( "Test" );
function debug_to_console( $data ) {
    $output = $data;
    if ( is_array( $output ) )
        $output = implode( ',', $output);

    echo "<script>console.log( 'Debug Objects: " . $output . "' );</script>";
}

$user = "RWTQ";
define('DIRECTORY',"");
?>
<!DOCTYPE html>
<img src="<? echo DIRECTORY ;?>blueprint.bmp" width="480" height="400" title="Logo" alt="Logo" /> 
<?php  
$query8="DROP TABLE IF EXISTS `chart_type`  " or die(mysql_error());
$query="SELECT * FROM `artikelen` where Type  = 'STR'  " or die(mysql_error());
$query2="SELECT * FROM `artikelen` where ItemName like '%GLL%'  " or die(mysql_error());
$query3="SELECT * FROM `artikelen` where ItemName like '%SPD%'  " or die(mysql_error());
$query7="CREATE TABLE `chart_type` ( chart  VARCHAR(32) ,  title  VARCHAR(32) , shape  VARCHAR(32) , kolommen  int(6), totaal  int(6) , start int(6) ) ;" or die(mysql_error());
$query6="INSERT INTO `chart_type`(`chart`, `title`, `shape`, `kolommen`, `totaal`, `start`) VALUES ('RING','VORM','pie',4,100,0)   " or die(mysql_error());

$drop=mysqli_query($connection,$query8);
if ($connection->query($drop) == TRUE) {
    echo "table dropped";
}
$create=mysqli_query($connection,$query7);
if ($connection->query($create) == TRUE) {
    echo "table created";
	mysqli_query($connection,$query6);
mysqli_query($connection,$query6);
//mysqli_query($connection,$query6);
}
	mysqli_query($connection,$query6);	
//	mysqli_query($connection,$query6);

$dropchartdata="DROP TABLE IF EXISTS `chart_data`  " or die(mysql_error());
$createchartdata="CREATE TABLE `chart_data` ( shape  VARCHAR(32), label1  VARCHAR(32) ,data2  VARCHAR(32)  ,col1 int(6), col2  int(6), col3  int(6), col4  int(6), col5  int(6), col6  int(6), totaal  int(6) , start int(6) ) ;" or die(mysql_error());
$insertchartdata="INSERT INTO `chart_data`(`shape`, `label1`, `data2`, `col1`, `col2`, `col3`, `col4`, `col5`, `col6`, `totaal`, `start`) VALUES ('shape','label','data',10,20,30,40,50,60,100, 0 )   " or die(mysql_error());

	mysqli_query($connection,$dropchartdata);
	mysqli_query($connection,$createchartdata);
	$y=1;
	for ($x = 1, $y=1; $x <= 20; $x++) {
	//$y++;
	$insertchartdata="INSERT INTO `chart_data`(`shape`, `label1`, `data2`, `col1`, `col2`, `col3`, `col4`, `col5`, `col6`, `totaal`, `start`) VALUES ('shape".$y."','label".$x."','data".$x."',".$x.",".$x++.",30,40,50,60,100, 0 )   " or die(mysql_error());
	mysqli_query($connection,$insertchartdata);
    echo "inserted : $y <br>";
	$y++;
} 
//	$insertgraphdata=mysqli_query($connection,$insertchartdata);
if ($connection->query($insertchartdata) === TRUE) {
    echo "data inserted";
} else {
    echo $insertchartdata." not inserted; insert went wrong: " . $connection->error;
}
$result=mysqli_query($connection,$query);
if (!$result || mysqli_num_rows($result) == 0);
$count1=mysqli_num_rows($result);

$row = mysqli_fetch_assoc($result);
$fields = array_keys($row);
//var_dump($fields);

$result_count=mysqli_query($connection,$query2);
//result may be false or true; trap false
if (!$result_count || mysqli_num_rows($result_count) == 0);
$count2=mysqli_num_rows($result_count);

$result_count3=mysqli_query($connection,$query3);
//result may be false or true; trap false
if (!$result_count3 || mysqli_num_rows($result_count3) == 0);
$count3=mysqli_num_rows($result_count3);

//$query4="SELECT * FROM `artikelen` where ItemName like '%ROR%'  " or die(mysql_error());
$query4="SELECT * FROM `artikelen` " or die(mysql_error());
$result_count2=mysqli_query($connection,$query4);
//result may be false or true; trap false
if (!$result_count || mysqli_num_rows($result_count2) == 0);
$count4=mysqli_num_rows($result_count2);

debug_to_console("start");
//debug_to_console( $result );
	
if (mysqli_num_rows($result)>0) {

$myfile = fopen(DIRECTORY."index222.php", "w") or die("Unable to open file!"); 	
 //=====================================================
 //================= start graphics file2 ==============
 //=====================================================
fwrite($myfile, "<!DOCTYPE html >");
fwrite($myfile, "<html>");
fwrite($myfile, "<head>");
fwrite($myfile, "<link rel=\"stylesheet\" type=\"text/css\" href=\"css/normalize.css\" />");
fwrite($myfile, "<link rel=\"stylesheet\" type=\"text/css\" href=\"css/demo.css\" />");
fwrite($myfile, "<link rel=\"stylesheet\" type=\"text/css\" href=\"css/component.css\" />");
fwrite($myfile, "<title>Generated by query </title>");
fwrite($myfile, "<style>");
fwrite($myfile, "body{");
fwrite($myfile, "background: #fff;");
fwrite($myfile, "color: #333;");
fwrite($myfile, "}");
fwrite($myfile, "a, a:visited, a:link, a:active{");
fwrite($myfile, "color: #333;");
fwrite($myfile, "}");
fwrite($myfile, "a:hover{");
fwrite($myfile, "color: #00f;");
fwrite($myfile, "}");
fwrite($myfile, ".charts_container{overflow: auto;");
fwrite($myfile, "width: 900px;");
fwrite($myfile, "height: 420px;");
fwrite($myfile, "margin: 10px auto;}");
//fwrite($myfile, ".chart_container_centered{");
fwrite($myfile, ".chart_container{");
fwrite($myfile, "text-align: center;");
fwrite($myfile, "width: 900px;");
fwrite($myfile, "height: 420px;");
fwrite($myfile, "margin: 10px auto;");
fwrite($myfile, "}");
fwrite($myfile, ".chart_container{");
fwrite($myfile, "width: 400px;");
fwrite($myfile, "height: 400px;");
fwrite($myfile, "margin: 0px 25px;");
fwrite($myfile, "float: left;");
fwrite($myfile, "}");
fwrite($myfile, ".footer{");
fwrite($myfile, "font-size: small;");
fwrite($myfile, "text-align: right;");
fwrite($myfile, "}");
fwrite($myfile, "</style>");
fwrite($myfile, "<script type=\"application/javascript\" src=\"awesomechart.js\"> </script>");
fwrite($myfile, "</head>");
fwrite($myfile, "<body>");
//fwrite($myfile, "<div class=\"chart_container_centered\" >");
fwrite($myfile, "<div class=\"chart_container\" >");
//fwrite($myfile, "<canvas id=\"chartCanvas1\" width=\"600\" height=\"400\">");
fwrite($myfile, "<canvas id=\"chartCanvas13\" width=\"600\" height=\"400\">");
fwrite($myfile, " Your web-browser does not support the HTML 5 canvas element.");
fwrite($myfile, "</canvas>");
fwrite($myfile, "</div>");
 //=====================================================
 //=================  labels and data ==================
 //=====================================================
 /*var chart13 = new AwesomeChart('chartCanvas13');
            chart13.chartType = "pareto";
            chart13.title = "RW Technology distribution";
            chart13.data = [51.62,31.3,10.06,4.27,1.96,0.78];
            chart13.labels = ['IE','Firefox','Chrome','Safari','Opera','Other'];
            chart13.draw();
			*/
fwrite($myfile, "<script type=\"application/javascript\">");
fwrite($myfile, "var chart13 = new AwesomeChart('chartCanvas13');");
fwrite($myfile, "chart13.chartType = \"pareto\" ;");
fwrite($myfile, "chart13.title = \"Available Data for Customer '".$user."' \";");
fwrite($myfile, "chart13.data = [".$count1.",".$count2.",".$count3.",".$count4."];");
fwrite($myfile, "chart13.labels = ['STR','GLL','SPD','ROR'];");
fwrite($myfile, "chart13.draw();");
fwrite($myfile, "</script>");
//fwrite($myfile, "");
//fwrite($myfile, "");
}
else
{
$myfile = fopen(DIRECTORY."index222.php", "w") or die("Unable to open file!"); 
fwrite($myfile, "<h3>No Count Results found.</h3>");
}

 //=====================================================
 //================= start graphics file3 ==============
 //=====================================================
//if we get any results we show them in table data
$query = "SELECT * FROM `artikelen`";
$result=mysqli_query($connection,$query);
if (mysqli_num_rows($result)>0)
{
  //while we going through each row we display info
  //while($row=mysqli_fetch_assoc($result)):
  ?>
  <table>
  <tr>
    <td align="center"><?php echo $row["ItemNumber"];   ?></td>
    <td align="center"><?php echo $row["ItemName"];  ?></td>
    <td align="center"><?php echo $row["Price"];   ?></td>
  </tr>
  <?php //endwhile;?>
</table>
<?php 
//if we can't get results we show information
}
else
{ ?>
<h3>No Results found.</h3>
<?php 
}  
$myfile = fopen(DIRECTORY."index33.php", "w") or die("Unable to open file!");
fwrite($myfile, "<table width=\"100%\" border=\"0\">");
fwrite($myfile, "<tr>");
fwrite($myfile, "<td align=\"center\">Id</td>");
fwrite($myfile, "<td align=\"center\">Omschr</td>");
fwrite($myfile, "<td align=\"center\">Prijs</td>");
fwrite($myfile, "<tr>");

fwrite($myfile, "<td align=\"center\">" . "ItemNumber" . "</td>");
fwrite($myfile, "<td align=\"center\">" . "ItemName" . "</td>");
fwrite($myfile, "<td align=\"center\">" . "Price" . "</td>");

$result=mysqli_query($connection,$query);
if (mysqli_num_rows($result)>0)
{
 //=====================================================
 //=================  labels and data ==================
 //=====================================================
  while($row=mysqli_fetch_assoc($result)):
	fwrite($myfile, "<tr>");
	fwrite($myfile, "<td align=\"center\">" . $row["ItemNumber"] . "</td>");
	fwrite($myfile, "<td align=\"center\">" . $row["ItemName"] . "</td>");
	fwrite($myfile, "<td align=\"center\">" . $row["Price"] . "</td>");
	fwrite($myfile, "<tr>");
  endwhile;

  fwrite($myfile, "</table>");
}
?>

</body>
</html>